// Theo doi goi SDT, Khach hang, Nhan vien.
import { StyleSheet } from "react-native";

export const callLogsStyles = StyleSheet.create({
  callLogListContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 96,
  },
  callLogHeroCard: {
    padding: 18,
    borderRadius: 20,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
    marginBottom: 12,
    shadowColor: "#0F172A",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  callLogHeroTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  callLogBellButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  callLogBellButtonOn: {
    backgroundColor: "#F37021",
    borderColor: "#F37021",
    shadowColor: "#F37021",
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  callLogStatsRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 16,
  },
  callLogPanel: {
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
    marginBottom: 12,
    shadowColor: "#0F172A",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  callLogToolbar: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  callLogEmployeeList: {
    marginTop: 10,
    gap: 8,
  },
  callLogEmployeeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#F8FAFC",
  },
  callLogEmployeeRowSelected: {
    borderColor: "#F37021",
    backgroundColor: "#FFF7ED",
  },
  callLogEmployeeAvatar: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#17305D",
    alignItems: "center",
    justifyContent: "center",
  },
  callLogEmployeeAvatarActive: {
    backgroundColor: "#F37021",
  },
  callLogEmployeeAvatarText: {
    fontSize: 13,
    fontWeight: "900",
    color: "#ffffff",
  },
  callLogEmployeeMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  callLogEmployeeTextWrap: {
    flex: 1,
  },
  callLogEmployeeName: {
    fontSize: 14,
    fontWeight: "800",
    color: "#17305D",
  },
  callLogEmployeeMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  callLogEmployeeCountBadge: {
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: "#E2E8F0",
  },
  callLogEmployeeCountBadgeActive: {
    backgroundColor: "#FFE4CC",
  },
  callLogEmployeeCountBadgeText: {
    fontSize: 11,
    fontWeight: "900",
    color: "#64748B",
  },
  callLogEmployeeCountBadgeTextActive: {
    color: "#B54708",
  },
  callLogEmployeeMeta: {
    fontSize: 12,
    color: "#64748B",
  },
  callLogWatchButton: {
    width: 36,
    height: 36,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  callLogWatchButtonOn: {
    backgroundColor: "#15428B",
    borderColor: "#15428B",
    shadowColor: "#15428B",
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  callLogHint: {
    marginTop: 8,
    fontSize: 12,
    color: "#64748B",
  },
  callLogPresetRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 8,
  },
  callLogPresetButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#ffffff",
  },
  callLogPresetButtonOn: {
    backgroundColor: "#17305D",
    borderColor: "#17305D",
  },
  callLogPresetText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#475569",
  },
  callLogPresetTextOn: {
    color: "#ffffff",
  },
  callLogCalendarButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#F37021",
    backgroundColor: "#ffffff",
  },
  callLogCalendarButtonOn: {
    backgroundColor: "#F37021",
    borderColor: "#F37021",
  },
  callLogDayHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 6,
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  callLogDayHeaderText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#17305D",
  },
  callLogDayHeaderCount: {
    fontSize: 12,
    fontWeight: "700",
    color: "#F37021",
  },
  callLogCollapseHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 4,
  },
  callLogCollapseTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#17305D",
  },
  callLogCollapseSummary: {
    fontSize: 12,
    color: "#64748B",
    marginTop: 2,
  },
  callLogChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 8,
  },
  callLogChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "#EDF3FF",
    borderWidth: 1,
    borderColor: "#BFD3F2",
  },
  callLogChipText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#15428B",
  },
  calOverlay: {
    flex: 1,
    backgroundColor: "rgba(10, 22, 44, 0.5)",
    justifyContent: "center",
    padding: 20,
  },
  calSheet: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 16,
  },
  calHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  calMonthTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#17305D",
  },
  calNavButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EDF1F9",
  },
  calWeekRow: {
    flexDirection: "row",
    marginBottom: 4,
  },
  calWeekDayText: {
    flex: 1,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "800",
    color: "#64748B",
  },
  calDayCell: {
    flex: 1,
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    margin: 1,
  },
  calDayInRange: {
    backgroundColor: "#FDE7D8",
  },
  calDaySelected: {
    backgroundColor: "#F37021",
  },
  calDayText: {
    fontSize: 14,
    color: "#17305D",
  },
  calDayTextMuted: {
    color: "#C2CBD9",
  },
  calDayTextSelected: {
    color: "#ffffff",
    fontWeight: "800",
  },
  calRangeText: {
    textAlign: "center",
    fontSize: 13,
    fontWeight: "700",
    color: "#17305D",
    marginVertical: 10,
  },
  calFooterRow: {
    flexDirection: "row",
    gap: 10,
  },
  calCancelButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#ffffff",
  },
  calCancelText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#475569",
  },
  calApplyButton: {
    flex: 2,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#F37021",
  },
  calApplyText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#ffffff",
  },
  callLogRow: {
    padding: 14,
    borderRadius: 16,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
    marginBottom: 10,
    shadowColor: "#0F172A",
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  callLogRowTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  callLogStaffBadge: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "#EEF2FF",
  },
  callLogStaffBadgeText: {
    fontSize: 11,
    fontWeight: "900",
    color: "#15428B",
  },
  callLogTime: {
    flex: 1,
    textAlign: "right",
    fontSize: 12,
    color: "#64748B",
  },
  callLogStaffName: {
    marginTop: 8,
    fontSize: 15,
    fontWeight: "800",
    color: "#17305D",
  },
  callLogAddress: {
    marginTop: 5,
    fontSize: 15,
    fontWeight: "700",
    color: "#334155",
  },
  callLogMeta: {
    marginTop: 5,
    fontSize: 13,
    lineHeight: 19,
    color: "#64748B",
  },
  callLogPhoneRow: {
    marginTop: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  callLogPhone: {
    flex: 1,
    fontSize: 15,
    fontWeight: "900",
    color: "#F37021",
  },
  callLogDetailOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(15, 23, 42, 0.42)",
  },
  callLogDetailSheet: {
    maxHeight: "86%",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 20,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    backgroundColor: "#F8FBFF",
  },
  callLogDetailHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  callLogDetailTitleWrap: {
    flex: 1,
  },
  callLogDetailTitle: {
    marginTop: 4,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "900",
    color: "#17305D",
  },
  callLogDetailSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: "#64748B",
  },
  callLogDetailCloseButton: {
    width: 42,
    height: 42,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  callLogDetailLoading: {
    minHeight: 220,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  callLogDetailListContent: {
    paddingBottom: 16,
  },
});
