// Man hinh Khach hang.
import { StyleSheet } from "react-native";

export const customersStyles = StyleSheet.create({
  khSearchWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginHorizontal: 16,
    marginTop: 12,
    paddingHorizontal: 12,
    minHeight: 46,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#DCE4F2",
    backgroundColor: "#ffffff",
  },
  khSearchInput: {
    flex: 1,
    fontSize: 14.5,
    color: "#17305D",
    paddingVertical: 10,
  },
  khTotal: {
    fontSize: 12,
    color: "#8CA0C3",
    paddingHorizontal: 16,
    marginTop: 6,
    marginBottom: 8,
  },
  khCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginHorizontal: 16,
    marginBottom: 8,
    paddingVertical: 11,
    paddingHorizontal: 12,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#E4EAF5",
    backgroundColor: "#ffffff",
  },
  khAvatarSmall: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#15428B",
  },
  khAvatarText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "800",
  },
  khName: {
    fontSize: 14.5,
    fontWeight: "700",
    color: "#17305D",
  },
  khMeta: {
    fontSize: 12,
    color: "#6B7FA3",
    marginTop: 2,
  },
  khBadge: {
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: "#FDEAD9",
  },
  khBadgeText: {
    fontSize: 11.5,
    fontWeight: "700",
    color: "#F37021",
  },
  khBackRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  khBackText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#15428B",
  },
  khDetailHero: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginHorizontal: 16,
    marginBottom: 10,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#E4EAF5",
  },
  khAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#15428B",
  },
  khDetailName: {
    fontSize: 17,
    fontWeight: "800",
    color: "#17305D",
  },
  khPhoneRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginHorizontal: 16,
    marginBottom: 8,
    paddingHorizontal: 14,
    minHeight: 46,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#FBD8B9",
    backgroundColor: "#FFF7F0",
  },
  khPhoneText: {
    flex: 1,
    fontSize: 15,
    fontWeight: "800",
    color: "#17305D",
  },
  khPhoneHint: {
    fontSize: 11,
    color: "#B9822F",
  },
  khInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginHorizontal: 16,
    marginBottom: 6,
  },
  khInfoText: {
    flex: 1,
    fontSize: 13,
    color: "#44536E",
  },
  khNoteBox: {
    marginHorizontal: 16,
    marginBottom: 8,
    padding: 12,
    borderRadius: 14,
    backgroundColor: "#F4F7FC",
  },
  khNoteText: {
    fontSize: 13,
    color: "#44536E",
  },
  khSectionTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#17305D",
    paddingHorizontal: 16,
    marginTop: 14,
    marginBottom: 8,
  },
  khEmpty: {
    fontSize: 13,
    color: "#8CA0C3",
    paddingHorizontal: 16,
  },
  khPropCard: {
    marginHorizontal: 16,
    marginBottom: 8,
    padding: 12,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#E4EAF5",
    backgroundColor: "#ffffff",
  },
  khPropTitle: {
    fontSize: 13.5,
    fontWeight: "700",
    color: "#17305D",
  },
});
