// Man hinh Nhap nha (luoi giong Landsoft desktop) + hang cho + dan tin Cho Tot.
import { StyleSheet } from "react-native";

export const formStyles = StyleSheet.create({
  formHeroCard: {
    marginBottom: 14,
    borderRadius: 24,
    padding: 18,
    backgroundColor: "#EAF1FB",
    borderWidth: 1,
    borderColor: "#D8E3F3",
  },
  formHeroEyebrow: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0,
    color: "#7C8BA1",
    marginBottom: 8,
  },
  formHeroTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#17305D",
    lineHeight: 28,
  },
  formHeroDescription: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 21,
    color: "#53657D",
  },
  formHeroChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 14,
  },
  formHeroChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
  },
  formHeroChipDone: {
    backgroundColor: "#ECFDF5",
    borderColor: "#A7F3D0",
  },
  formHeroChipPending: {
    backgroundColor: "#FFF7ED",
    borderColor: "#FED7AA",
  },
  formHeroChipText: {
    fontSize: 12,
    fontWeight: "700",
  },
  formHeroChipTextDone: {
    color: "#047857",
  },
  formHeroChipTextPending: {
    color: "#C2410C",
  },
  draftHint: {
    marginBottom: 12,
  },
  draftHintText: {
    fontSize: 12,
    color: "#7C8BA1",
  },
  submitPanel: {
    marginBottom: 18,
    padding: 16,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    gap: 8,
  },
  submitPanelTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#17305D",
  },
  submitPanelDescription: {
    fontSize: 13,
    lineHeight: 20,
    color: "#64748B",
    marginBottom: 4,
  },
  createReadyRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexWrap: "wrap",
  },
  createReadyChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: "#F1F5F9",
    borderWidth: 1,
    borderColor: "#CBD5E1",
  },
  createReadyChipDone: {
    backgroundColor: "#DCFCE7",
    borderColor: "#86EFAC",
  },
  createReadyChipText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#94A3B8",
  },
  createReadyChipTextDone: {
    color: "#16A34A",
  },
  createSavingText: {
    fontSize: 12,
    color: "#94A3B8",
    marginLeft: "auto",
  },
  createDimsRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
  },
  createDimsField: {
    flex: 1,
  },
  createDimsSep: {
    fontSize: 18,
    color: "#94A3B8",
    paddingBottom: 10,
    fontWeight: "500",
  },
  quickChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  quickChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#D9E2EC",
    backgroundColor: "#ffffff",
  },
  quickChipActive: {
    borderColor: "#F37021",
    backgroundColor: "#FFF3EC",
  },
  quickChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#53657D",
  },
  quickChipTextActive: {
    color: "#F37021",
  },
  typeToggleRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 6,
  },
  typeToggleButton: {
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#D9E2EC",
    backgroundColor: "#ffffff",
  },
  typeToggleButtonActive: {
    borderColor: "#F37021",
    backgroundColor: "#FFF3EC",
  },
  typeToggleText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#53657D",
  },
  typeToggleTextActive: {
    color: "#F37021",
  },
  lsFormTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#17305D",
    paddingHorizontal: 16,
    marginTop: 4,
  },
  lsFormSubtitle: {
    fontSize: 13,
    color: "#6B7FA3",
    paddingHorizontal: 16,
    marginTop: 2,
    marginBottom: 4,
  },
  chototPasteButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 2,
    minHeight: 46,
    borderRadius: 18,
    backgroundColor: "#15428B",
  },
  chototPasteButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  chototPasteHint: {
    fontSize: 11.5,
    color: "#8CA0C3",
    paddingHorizontal: 16,
    marginBottom: 6,
  },
  pasteRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 6,
  },
  pasteBatchButton: {
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: "#15428B",
  },
  pasteSingleButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 13,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#BFD3F2",
    backgroundColor: "#F7FAFF",
  },
  pasteSingleButtonText: {
    fontSize: 13.5,
    fontWeight: "700",
    color: "#15428B",
  },
  queueBox: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    padding: 12,
    marginBottom: 12,
  },
  queueHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  queueTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#17305D",
  },
  queueClear: {
    fontSize: 12.5,
    fontWeight: "700",
    color: "#C0392B",
  },
  queueItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E4EAF5",
    backgroundColor: "#FBFCFE",
    marginBottom: 6,
  },
  queueItemActive: {
    borderColor: "#F37021",
    backgroundColor: "#FFF6F1",
  },
  queueItemTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#17305D",
  },
  queueItemSub: {
    fontSize: 12.5,
    color: "#5B6B85",
    marginTop: 1,
  },
  queueItemMissing: {
    fontSize: 11.5,
    fontWeight: "700",
    color: "#C0392B",
    marginTop: 2,
  },
  queueItemReady: {
    fontSize: 11.5,
    fontWeight: "700",
    color: "#1D9E75",
    marginTop: 2,
  },
  queueRemove: {
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  queueSaveAll: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: "#F37021",
    marginTop: 4,
  },
  queueSaveAllText: {
    fontSize: 15,
    fontWeight: "800",
    color: "#ffffff",
  },
  queueHint: {
    fontSize: 11,
    color: "#8A97AC",
    textAlign: "center",
    marginTop: 7,
  },
  addToQueueButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#BFD3F2",
    backgroundColor: "#F7FAFF",
    marginBottom: 8,
  },
  addToQueueText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#15428B",
  },
  wfScreen: {
    backgroundColor: "#ECEEF1",
  },
  wfGroup: {
    marginHorizontal: 8,
    marginTop: 10,
    paddingHorizontal: 8,
    paddingTop: 6,
    paddingBottom: 8,
    borderWidth: 1,
    borderColor: "#B9C0CB",
    borderRadius: 3,
    backgroundColor: "#F4F5F7",
  },
  wfGroupTitle: {
    fontSize: 13.5,
    fontWeight: "700",
    color: "#1F3B70",
    marginBottom: 4,
  },
  wfRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 5,
    minHeight: 34,
  },
  wfLabel: {
    width: 112,
    fontSize: 12.5,
    color: "#222B3A",
  },
  wfControl: {
    flex: 1,
  },
  wfDimRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 5,
  },
  wfDimCell: {
    flex: 1,
  },
  wfDimLabel: {
    fontSize: 12.5,
    color: "#222B3A",
    marginBottom: 4,
  },
  wfInput: {
    borderWidth: 1,
    borderColor: "#A8B0BC",
    borderRadius: 2,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 8,
    paddingVertical: 6,
    fontSize: 13.5,
    color: "#111827",
    minHeight: 34,
  },
  wfInputDisabled: {
    backgroundColor: "#E8EAED",
    color: "#5B6472",
  },
  wfInputRequiredPhone: {
    backgroundColor: "#FFD2D2",
  },
  wfInputDone: {
    backgroundColor: "#E9F7EC",
    borderColor: "#8FCF9F",
  },
  wfPickerWrapDone: {
    backgroundColor: "#E9F7EC",
    borderColor: "#8FCF9F",
  },
  wfPickerWrap: {
    borderWidth: 1,
    borderColor: "#A8B0BC",
    borderRadius: 2,
    backgroundColor: "#FFFFFF",
    height: 44,
    justifyContent: "center",
    overflow: "hidden",
  },
  wfRadioRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  wfRadioItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  wfRadioOuter: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#5B6472",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  wfRadioInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#1F5FBF",
  },
  wfRadioText: {
    fontSize: 13,
    color: "#111827",
  },
  wfCheckRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    flexWrap: "wrap",
  },
  wfCheckItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  wfCheckBox: {
    width: 15,
    height: 15,
    borderWidth: 1.2,
    borderColor: "#5B6472",
    borderRadius: 2,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  wfCheckBoxChecked: {
    backgroundColor: "#1F5FBF",
    borderColor: "#1F5FBF",
  },
  wfCheckText: {
    fontSize: 13,
    color: "#111827",
  },
  wfBtnRow: {
    flexDirection: "row",
    gap: 8,
    marginHorizontal: 8,
    marginTop: 12,
  },
  wfBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 40,
    borderWidth: 1,
    borderColor: "#8F98A6",
    borderRadius: 3,
    backgroundColor: "#F7F8FA",
  },
  wfBtnPrimary: {
    backgroundColor: "#DEE9F8",
    borderColor: "#4A7BC8",
  },
  wfBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1F3B70",
  },
  wfThuongLuong: {
    color: "#D00000",
    fontSize: 13,
    fontWeight: "800",
  },
  wfHint: {
    fontSize: 11.5,
    color: "#6B7280",
    marginTop: 2,
  },
  lsThuongLuongLabel: {
    color: "#D32F2F",
    fontSize: 13.5,
    fontWeight: "800",
    marginTop: 6,
  },
  chototPickerBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15, 30, 60, 0.55)",
    justifyContent: "flex-end",
  },
  chototPickerSheet: {
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingTop: 16,
    paddingBottom: 24,
    paddingHorizontal: 16,
    maxHeight: "75%",
  },
  chototPickerHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  chototPickerTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#17305D",
  },
  chototPickerList: {
    flexGrow: 0,
  },
  chototPickerItem: {
    borderWidth: 1,
    borderColor: "#DCE4F2",
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 10,
    backgroundColor: "#F8FAFE",
  },
  chototPickerItemPressed: {
    backgroundColor: "#E8F0FE",
    borderColor: "#15428B",
  },
  chototPickerItemTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#17305D",
  },
  chototPickerItemSub: {
    fontSize: 12.5,
    color: "#6B7FA3",
    marginTop: 3,
  },
  chototPickerCancel: {
    marginTop: 6,
    minHeight: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EDF1F9",
  },
  chototPickerCancelText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#17305D",
  },
  lsGiaQuyDoi: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1565C0",
    marginTop: 4,
  },
  inputDuplicate: {
    borderColor: "#DC2626",
    borderWidth: 1.5,
    backgroundColor: "#FFE4E4",
  },
  lsPhoneDupWarn: {
    fontSize: 12,
    fontWeight: "700",
    color: "#DC2626",
    marginTop: 4,
  },
  lsPhoneStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  lsPhoneChecking: {
    fontSize: 12,
    color: "#6B7FA3",
  },
  lsPhoneOk: {
    fontSize: 12,
    fontWeight: "600",
    color: "#16A34A",
    marginTop: 4,
  },
  lsPhoneOwnerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 3,
  },
  lsPhoneOwner: {
    fontSize: 12,
    fontWeight: "600",
    color: "#15428B",
  },
  lsStreetDropdown: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#C5CEE0",
    borderRadius: 10,
    marginTop: 4,
    overflow: "hidden",
  },
  lsStreetItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 11,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#EEF1F6",
  },
  lsStreetItemText: {
    fontSize: 14,
    color: "#17305D",
  },
  lsStreetHint: {
    fontSize: 11,
    color: "#94A3B8",
    marginTop: 3,
  },
  lsGridRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  lsGridCell: {
    flexGrow: 1,
    flexBasis: "47%",
  },
  lsCellLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#53657D",
    marginBottom: 5,
  },
  lsCheckGroup: {
    flexDirection: "row",
    gap: 18,
    marginTop: 4,
  },
  lsCheckRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 6,
  },
  lsCheckBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: "#B6C2D4",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  lsCheckBoxOn: {
    backgroundColor: "#F37021",
    borderColor: "#F37021",
  },
  lsCheckLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: "#17305D",
  },
  lsOpenFullButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 4,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#F3702155",
    backgroundColor: "#FFF3EC",
  },
  lsOpenFullTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#F37021",
  },
  lsOpenFullDesc: {
    fontSize: 12,
    color: "#9A6B4F",
    marginTop: 1,
  },
});
