// Man hinh King Land.
import { StyleSheet } from "react-native";

export const kinglandStyles = StyleSheet.create({
  // ===== King Land desktop-style grid =====
  klRoot: {
    flex: 1,
    backgroundColor: "#EDEFF2",
  },
  klTitleBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#2B2F36",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  klTitleText: {
    color: "#E8EAED",
    fontSize: 11,
    fontWeight: "600",
    flex: 1,
  },
  klMenuBar: {
    backgroundColor: "#F4F5F7",
    borderBottomWidth: 1,
    borderBottomColor: "#C9CED6",
    flexGrow: 0,
  },
  klMenuItem: {
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  klMenuText: {
    fontSize: 10.5,
    fontWeight: "700",
    color: "#2A3646",
  },
  klTabStrip: {
    flexDirection: "row",
    backgroundColor: "#E3E6EB",
    paddingTop: 4,
    paddingHorizontal: 6,
    gap: 4,
  },
  klTabActive: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: "#C9CED6",
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  klTabInactive: {
    backgroundColor: "#D6DAE1",
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  klTabText: {
    fontSize: 10.5,
    fontWeight: "800",
    color: "#17305D",
  },
  klTabTextInactive: {
    fontSize: 10.5,
    fontWeight: "700",
    color: "#5B6572",
  },
  klFilterBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#D5DAE1",
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  klStatusPickerWrap: {
    flex: 1.2,
    borderWidth: 1,
    borderColor: "#C9CED6",
    borderRadius: 4,
    height: 38,
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  klStatusPicker: {
    marginVertical: -8,
  },
  klSearchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#C9CED6",
    borderRadius: 4,
    height: 38,
    paddingHorizontal: 8,
    fontSize: 12,
    backgroundColor: "#FFFFFF",
  },
  klFilterButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderWidth: 1,
    borderColor: "#B9C2CF",
    borderRadius: 4,
    paddingHorizontal: 10,
    height: 38,
    backgroundColor: "#F4F5F7",
  },
  klFilterButtonText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#17305D",
  },
  klToolbar: {
    backgroundColor: "#F8F9FA",
    borderBottomWidth: 1,
    borderBottomColor: "#D5DAE1",
    flexGrow: 0,
  },
  klToolButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 7,
    borderRightWidth: 1,
    borderRightColor: "#E3E6EB",
  },
  klToolButtonText: {
    fontSize: 10.5,
    fontWeight: "600",
    color: "#2A3646",
  },
  klGridArea: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  klHeaderRow: {
    flexDirection: "row",
    backgroundColor: "#E9ECF1",
    borderBottomWidth: 1,
    borderBottomColor: "#B9C2CF",
  },
  klHeaderCell: {
    fontSize: 10,
    fontWeight: "800",
    color: "#2A3646",
    paddingHorizontal: 5,
    paddingVertical: 7,
    borderRightWidth: 1,
    borderRightColor: "#D5DAE1",
  },
  klRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#EDEFF2",
    backgroundColor: "#FFFFFF",
  },
  klRowAlt: {
    backgroundColor: "#F7F9FB",
  },
  klRowSelected: {
    backgroundColor: "#D8E6FA",
  },
  klCell: {
    fontSize: 10.5,
    color: "#232B36",
    paddingHorizontal: 5,
    paddingVertical: 8,
    borderRightWidth: 1,
    borderRightColor: "#F0F2F5",
  },
  klCellPrice: {
    fontWeight: "800",
    color: "#17305D",
  },
  klLoadingWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 14,
  },
  klLoadingText: {
    fontSize: 11.5,
    color: "#5B6572",
  },
  klFooterBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F4F5F7",
    borderTopWidth: 1,
    borderTopColor: "#C9CED6",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  klCountBox: {
    borderWidth: 1,
    borderColor: "#B9C2CF",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 3,
  },
  klCountText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#17305D",
  },
  klFooterHint: {
    fontSize: 10.5,
    color: "#5B6572",
  },
  klDetailPanel: {
    maxHeight: 230,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#B9C2CF",
  },
  klDetailTabs: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E9ECF1",
    borderBottomWidth: 1,
    borderBottomColor: "#C9CED6",
  },
  klDetailTab: {
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  klDetailTabActive: {
    backgroundColor: "#FFFFFF",
    borderTopWidth: 2,
    borderTopColor: "#F37021",
  },
  klDetailTabText: {
    fontSize: 10.5,
    fontWeight: "600",
    color: "#5B6572",
  },
  klDetailTabTextActive: {
    color: "#17305D",
    fontWeight: "800",
  },
  klDetailClose: {
    marginLeft: "auto",
    padding: 8,
  },
  klDetailBody: {
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  klDetailTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: "#17305D",
    marginBottom: 3,
  },
  klDetailLine: {
    fontSize: 11,
    color: "#334155",
    marginBottom: 2,
  },
  klDetailDescription: {
    fontSize: 11,
    color: "#475569",
    marginTop: 4,
    marginBottom: 10,
  },
  klNoteRow: {
    borderBottomWidth: 1,
    borderBottomColor: "#EDEFF2",
    paddingVertical: 5,
  },
  klNoteMeta: {
    fontSize: 10,
    color: "#8090A6",
    marginBottom: 1,
  },
  klNoteContent: {
    fontSize: 11,
    color: "#334155",
  },
});
