// Thanh tieu de + menu 3 gach + tab bar.
import { StyleSheet } from "react-native";

export const navStyles = StyleSheet.create({
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    backgroundColor: "#ffffff",
    gap: 12,
  },
  headerTextGroup: {
    flex: 1,
  },
  headerActions: {
    alignItems: "flex-end",
    gap: 8,
  },
  headerEyebrow: {
    fontSize: 11,
    fontWeight: "700",
    color: "#17305D",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#17305D",
  },
  headerSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: "#7C8BA1",
  },
  userPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#F7F9FC",
    borderWidth: 1,
    borderColor: "#E3EAF3",
  },
  userAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#17305D",
  },
  userAvatarText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
  },
  userPillTextGroup: {
    alignItems: "flex-start",
  },
  userPillName: {
    fontSize: 13,
    fontWeight: "800",
    color: "#17305D",
  },
  userPillRole: {
    fontSize: 12,
    color: "#7C8BA1",
    fontWeight: "600",
  },
  logoutPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
  },
  logoutPillText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#17305D",
  },
  tabBar: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 14,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    backgroundColor: "#ffffff",
  },
  tabButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F7F9FC",
    borderWidth: 1,
    borderColor: "#E5ECF4",
  },
  tabButtonIcon: {
    marginBottom: 4,
  },
  tabButtonActive: {
    backgroundColor: "#17305D",
    borderColor: "#17305D",
  },
  tabButtonText: {
    color: "#53657D",
    fontWeight: "700",
    fontSize: 12,
  },
  tabButtonTextActive: {
    color: "#ffffff",
  },
  menuButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EDF1F9",
    marginRight: 10,
  },
  headerCompact: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    backgroundColor: "#ffffff",
  },
  headerCompactTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#17305D",
  },
  drawerBackdrop: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "rgba(10, 22, 44, 0.45)",
  },
  drawerPanel: {
    width: 292,
    height: "100%",
    backgroundColor: "#FFFFFF",
    paddingTop: 46,
    borderTopRightRadius: 18,
    borderBottomRightRadius: 18,
  },
  drawerHeader: {
    paddingHorizontal: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#E4EAF5",
  },
  drawerBrand: {
    fontSize: 12,
    fontWeight: "800",
    color: "#F37021",
    letterSpacing: 1,
  },
  drawerUser: {
    fontSize: 16,
    fontWeight: "800",
    color: "#17305D",
    marginTop: 4,
  },
  drawerRole: {
    fontSize: 12,
    color: "#6B7FA3",
    marginTop: 2,
  },
  drawerAccountBox: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#E4EAF5",
  },
  drawerAccountTitle: {
    fontSize: 11,
    fontWeight: "800",
    color: "#8A97AC",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    marginBottom: 8,
    marginLeft: 4,
  },
  drawerAccountRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E4EAF5",
    backgroundColor: "#FFFFFF",
    marginBottom: 6,
  },
  drawerAccountRowActive: {
    backgroundColor: "#EDF3FF",
    borderColor: "#BFD3F2",
  },
  drawerAccountDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "#C2CBD9",
    alignItems: "center",
    justifyContent: "center",
  },
  drawerAccountDotActive: {
    backgroundColor: "#15428B",
    borderColor: "#15428B",
  },
  drawerAccountName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#2A3A55",
  },
  drawerAccountNameActive: {
    color: "#15428B",
    fontWeight: "800",
  },
  drawerAccountCode: {
    fontSize: 11.5,
    color: "#8A97AC",
    marginTop: 1,
  },
  drawerAccountBadge: {
    fontSize: 10.5,
    fontWeight: "700",
    color: "#15428B",
  },
  drawerAddAccount: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 9,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#BFD3F2",
    borderStyle: "dashed",
    backgroundColor: "#F7FAFF",
  },
  drawerAddAccountText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#15428B",
  },
  drawerAccountHint: {
    fontSize: 10.5,
    color: "#9AA6B8",
    textAlign: "center",
    marginTop: 7,
  },
  drawerItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 13,
    paddingHorizontal: 18,
  },
  drawerItemActive: {
    backgroundColor: "#EDF3FF",
    borderRightWidth: 3,
    borderRightColor: "#15428B",
  },
  drawerItemText: {
    fontSize: 15,
    color: "#2A3A55",
    fontWeight: "600",
  },
  drawerItemTextActive: {
    color: "#15428B",
    fontWeight: "800",
  },
  drawerLogout: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 15,
    paddingHorizontal: 18,
    borderTopWidth: 1,
    borderTopColor: "#E4EAF5",
    marginTop: "auto",
    marginBottom: 6,
  },
  drawerVersion: {
    paddingHorizontal: 18,
    paddingBottom: 16,
    fontSize: 11,
    color: "#9AA7BC",
  },
});
