// Man hinh Kho hang: o tim, bo loc, the tung can.
import { StyleSheet } from "react-native";

export const propertyListStyles = StyleSheet.create({
  searchInput: {
    flex: 1,
    minHeight: 48,
    paddingHorizontal: 0,
    paddingVertical: 10,
    fontSize: 15,
    color: "#17305D",
  },
  searchInputWrap: {
    flex: 1,
    minHeight: 48,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    paddingLeft: 16,
    paddingRight: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  phoneSearchWrap: {
    minHeight: 48,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: "#C7D6F0",
    backgroundColor: "#F4F8FF",
    paddingLeft: 16,
    paddingRight: 14,
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  searchInputIcon: {
    fontSize: 18,
    color: "#7C8BA1",
    marginTop: -1,
  },
  marketListContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 110,
  },
  marketListContentEmpty: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
  },
  marketOverview: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
    borderRadius: 28,
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: 12,
    gap: 12,
  },
  marketOverviewTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  marketOverviewBadge: {
    width: 46,
    height: 46,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EEF3FB",
  },
  marketOverviewTopActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  marketOverviewIconButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
  },
  marketOverviewIconButtonActive: {
    backgroundColor: "#17305D",
    borderColor: "#17305D",
  },
  marketOverviewAddButton: {
    minHeight: 42,
    borderRadius: 14,
    paddingHorizontal: 14,
    backgroundColor: "#F37021",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  marketOverviewAddButtonText: {
    fontSize: 13,
    fontWeight: "800",
    color: "#ffffff",
  },
  marketOverviewTextGroup: {
    gap: 2,
    flex: 1,
  },
  marketOverviewLabel: {
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    color: "#7C8BA1",
  },
  marketOverviewStat: {
    fontSize: 28,
    fontWeight: "800",
    color: "#17305D",
  },
  marketOverviewHint: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 19,
    color: "#7C8BA1",
  },
  searchPanel: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
    borderRadius: 28,
    padding: 12,
    marginBottom: 12,
    gap: 10,
  },
  searchToolbar: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  searchToolbarIconButton: {
    width: 46,
    height: 46,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  toolbarPillRow: {
    flexDirection: "row",
    gap: 10,
  },
  filterChipRow: {
    gap: 8,
    paddingTop: 2,
  },
  filterChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E8EEF5",
    backgroundColor: "#F7F9FC",
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  filterChipText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#425466",
  },
  filterPanel: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
    borderRadius: 24,
    padding: 14,
    marginBottom: 12,
  },
  filterPanelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  filterPanelTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#17305D",
  },
  filterGroupLabel: {
    marginTop: 4,
    marginBottom: 6,
    fontSize: 13,
    fontWeight: "800",
    color: "#17305D",
  },
  filterResetText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#F37021",
  },
  filterRangeRow: {
    flexDirection: "row",
    gap: 10,
  },
  filterRangeField: {
    flex: 1,
  },
  filterButtonRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
  },
  listHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    gap: 12,
  },
  listHeaderTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#17305D",
  },
  listHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  listHeaderCount: {
    fontSize: 13,
    fontWeight: "700",
    color: "#7C8BA1",
    backgroundColor: "#EEF3FB",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  listContainer: {
    paddingBottom: 20,
  },
  propertyRow: {
    marginBottom: 14,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    overflow: "hidden",
    shadowColor: "#17305D",
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  createFab: {
    position: "absolute",
    right: 16,
    bottom: 18,
    minHeight: 54,
    borderRadius: 20,
    paddingHorizontal: 18,
    backgroundColor: "#F37021",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    shadowColor: "#F37021",
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  createFabText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "800",
  },
  propertyCardTapArea: {
    overflow: "hidden",
  },
  propertyHero: {
    minHeight: 168,
    backgroundColor: "#E7EEF8",
    padding: 16,
    justifyContent: "space-between",
  },
  propertyHeroTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  propertyHeroStatus: {
    backgroundColor: "#ffffff",
  },
  propertyHeroTopActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  propertyCodePill: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  propertyCode: {
    fontSize: 13,
    fontWeight: "800",
    color: "#17305D",
  },
  propertyHeroBody: {
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 8,
  },
  propertyHeroIconWrap: {
    width: 82,
    height: 82,
    borderRadius: 26,
    backgroundColor: "#F9FBFE",
    alignItems: "center",
    justifyContent: "center",
  },
  propertyFavoriteBubble: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E4ECF6",
  },
  propertyHeroLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "#8B9AB0",
  },
  propCard: {
    backgroundColor: "#ffffff",
    marginHorizontal: 12,
    marginVertical: 4,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: "#E4ECF6",
    gap: 5,
    elevation: 2,
    shadowColor: "#17305D",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 3,
  },
  propCardRow1: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  propCardPrice: {
    fontSize: 18,
    fontWeight: "700",
    color: "#F37021",
    letterSpacing: -0.3,
  },
  propCardDims: {
    fontSize: 13,
    color: "#6B7FA3",
    fontWeight: "500",
    flex: 1,
  },
  propCardBadge: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 9,
    paddingVertical: 3,
  },
  propCardBadgeText: {
    fontSize: 11,
    fontWeight: "700",
  },
  propCardAddress: {
    fontSize: 14,
    fontWeight: "600",
    color: "#17305D",
    lineHeight: 20,
  },
  propCardContactRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 1,
  },
  propCardContact: {
    flex: 1,
    fontSize: 13,
    color: "#6B7FA3",
  },
  propCardDateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 1,
  },
  propCardDate: {
    fontSize: 12,
    color: "#94A3B8",
  },
  propCardPhoneBtn: {
    padding: 2,
  },
  compactCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: "#ffffff",
    marginHorizontal: 10,
    marginVertical: 3,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#E4ECF6",
    elevation: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  compactCardBody: {
    flex: 1,
    gap: 3,
  },
  compactCardMain: {
    fontSize: 14,
    fontWeight: "600",
    color: "#17305D",
    lineHeight: 20,
  },
  compactCardContactRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  compactCardContact: {
    flex: 1,
    fontSize: 13,
    color: "#4A6280",
  },
  compactCardPhoneBtn: {
    padding: 2,
  },
  propertyHeroContact: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "rgba(255,255,255,0.55)",
    borderTopWidth: 1,
    borderTopColor: "#D4E2F4",
  },
  propertyHeroContactBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#17305D",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  propertyHeroContactInitials: {
    fontSize: 13,
    fontWeight: "700",
    color: "#ffffff",
  },
  propertyHeroContactInfo: {
    flex: 1,
    gap: 2,
  },
  propertyHeroContactName: {
    fontSize: 13,
    fontWeight: "700",
    color: "#17305D",
  },
  propertyHeroContactPhone: {
    fontSize: 12,
    color: "#4A6280",
  },
  propertyHeroContactPhoneMissing: {
    fontSize: 12,
    color: "#A0AEC0",
    fontStyle: "italic",
  },
  propertyHeroPhoneButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#FFF1E7",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  propertyBody: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 14,
  },
  propertyPriceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 8,
  },
  propertyUpdatedChip: {
    borderRadius: 999,
    backgroundColor: "#FFF1E7",
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  propertyUpdatedChipText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#F37021",
  },
  propertyTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#17305D",
    lineHeight: 25,
    marginBottom: 6,
  },
  propertyLocation: {
    fontSize: 14,
    color: "#53657D",
    marginBottom: 8,
  },
  propertyPrice: {
    flex: 1,
    fontSize: 30,
    fontWeight: "800",
    color: "#17305D",
  },
  propertyFactsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 10,
  },
  propertyFact: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    backgroundColor: "#F7F9FC",
    borderWidth: 1,
    borderColor: "#E5ECF4",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  propertyFactText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#5A6A82",
  },
  propertyAddressPrimary: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: "800",
    color: "#17305D",
    marginBottom: 2,
  },
  propertyAddressSecondary: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
    color: "#7C8BA1",
    marginBottom: 8,
  },
  propertySnippet: {
    fontSize: 13,
    lineHeight: 20,
    color: "#53657D",
    marginBottom: 12,
  },
  propertyActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  propertyActionBar: {
    paddingHorizontal: 16,
    paddingBottom: 14,
    marginTop: -2,
  },
  propertyPrimaryAction: {
    flex: 1,
    minHeight: 46,
    borderRadius: 18,
    backgroundColor: "#F37021",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  propertyPrimaryActionText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#ffffff",
  },
  propertySecondaryAction: {
    flex: 1,
    minHeight: 46,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#F8FBFF",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  propertySecondaryActionText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#17305D",
  },
  listRow: {
    marginBottom: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#dbe3ef",
    backgroundColor: "#ffffff",
    padding: 14,
  },
  listRowTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  listRowCode: {
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
    color: "#0f766e",
  },
  listRowStatus: {
    fontSize: 12,
    color: "#475569",
  },
  listRowTitle: {
    marginTop: 4,
    fontSize: 16,
    fontWeight: "700",
    color: "#0f172a",
  },
  listRowMeta: {
    marginTop: 4,
    fontSize: 13,
    color: "#475569",
  },
  listRowDescription: {
    marginTop: 6,
    fontSize: 13,
    color: "#64748b",
  },
  // listing type toggle
  listingTypeRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  listingTypeButton: {
    flex: 1,
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#F7F9FC",
  },
  listingTypeButtonActive: {
    backgroundColor: "#17305D",
    borderColor: "#17305D",
  },
  listingTypeButtonText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#53657D",
  },
  listingTypeButtonTextActive: {
    color: "#ffffff",
  },
  listFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 18,
  },
  listFooterText: {
    fontSize: 13,
    color: "#8B9AB0",
  },
  loadMoreButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#F3702155",
    backgroundColor: "#FFF3EC",
  },
  loadMoreButtonText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#F37021",
  },
  rangeSliderTrackWrap: {
    height: 44,
    justifyContent: "center",
    position: "relative",
    marginTop: 6,
    marginBottom: 2,
  },
  rangeSliderTrack: {
    position: "absolute",
    left: 13,
    right: 13,
    top: 19.5,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#E2E8F0",
  },
  rangeSliderActive: {
    position: "absolute",
    top: 19.5,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#F37021",
  },
  rangeSliderThumb: {
    position: "absolute",
    top: 9,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "#ffffff",
    borderWidth: 2,
    borderColor: "#F37021",
    elevation: 3,
    shadowColor: "#17305D",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  rangeValueLabel: {
    fontSize: 13,
    color: "#6B7FA3",
    textAlign: "right",
    marginTop: 2,
  },
});
