// Man hinh chi tiet can + lich su + ghi chu.
import { StyleSheet } from "react-native";

export const propertyDetailStyles = StyleSheet.create({
  statusBadge: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: "700",
  },
  detailTopBar: {
    marginTop: 4,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  detailNavButton: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    minHeight: 42,
    paddingHorizontal: 14,
    borderRadius: 16,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
  },
  detailNavButtonText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#17305D",
  },
  detailTopBarActions: {
    flexDirection: "row",
    gap: 8,
  },
  detailTopIconButton: {
    width: 42,
    height: 42,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  detailDeleteButton: {
    width: 42,
    height: 42,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#F5B7B1",
    backgroundColor: "#FDEDEC",
    alignItems: "center",
    justifyContent: "center",
  },
  detailTopIconButtonPrimary: {
    width: 42,
    height: 42,
    borderRadius: 16,
    backgroundColor: "#F37021",
    alignItems: "center",
    justifyContent: "center",
  },
  detailHeroCard: {
    marginBottom: 0,
    borderRadius: 28,
    padding: 16,
    backgroundColor: "#E7EEF8",
    borderWidth: 1,
    borderColor: "#D8E3F3",
  },
  detailHeroTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    marginBottom: 22,
  },
  detailHeroMedia: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 170,
    gap: 12,
  },
  detailHeroMediaIconWrap: {
    width: 96,
    height: 96,
    borderRadius: 30,
    backgroundColor: "#F9FBFE",
    alignItems: "center",
    justifyContent: "center",
  },
  detailHeroMediaLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: "#8B9AB0",
  },
  detailSummaryCard: {
    marginTop: -28,
    marginBottom: 14,
    marginHorizontal: 8,
    padding: 16,
    borderRadius: 24,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
    shadowColor: "#17305D",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  detailHeroMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: 12,
    marginBottom: 12,
  },
  detailPrice: {
    flex: 1,
    fontSize: 28,
    fontWeight: "800",
    color: "#17305D",
  },
  detailArea: {
    fontSize: 16,
    fontWeight: "700",
    color: "#53657D",
  },
  detailChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 14,
  },
  detailChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E5ECF4",
    backgroundColor: "#F8FAFD",
  },
  detailChipText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#425466",
  },
  detailTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#17305D",
    lineHeight: 32,
    marginBottom: 6,
  },
  detailLocation: {
    fontSize: 14,
    color: "#64748B",
    marginBottom: 12,
  },
  detailAddressPrimary: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: "800",
    color: "#17305D",
    marginTop: 4,
    marginBottom: 2,
  },
  detailAddressSecondary: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
    color: "#6B7D96",
    marginBottom: 6,
  },
  detailActionRow: {
    flexDirection: "row",
    gap: 10,
  },
  detailActionPrimary: {
    flex: 1,
    minHeight: 46,
    borderRadius: 18,
    backgroundColor: "#F37021",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  detailActionPrimaryText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#ffffff",
  },
  detailActionSecondary: {
    flex: 1,
    minHeight: 46,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  detailActionSecondaryText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#17305D",
  },
  detailContactCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#D9E4F2",
    padding: 20,
    gap: 16,
    shadowColor: "#17305D",
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  detailContactHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  detailContactBadge: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#FFF3EB",
    alignItems: "center",
    justifyContent: "center",
  },
  detailContactHeaderText: {
    flex: 1,
    gap: 2,
  },
  detailContactEyebrow: {
    fontSize: 12,
    fontWeight: "700",
    color: "#F37021",
    textTransform: "uppercase",
  },
  detailContactOwner: {
    fontSize: 17,
    fontWeight: "700",
    color: "#17305D",
  },
  detailContactNumberWrap: {
    borderRadius: 22,
    backgroundColor: "#F8FBFF",
    borderWidth: 1,
    borderColor: "#D7E3F3",
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 6,
  },
  detailContactNumber: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "800",
    color: "#0F172A",
  },
  detailContactHint: {
    fontSize: 13,
    lineHeight: 18,
    color: "#6B7D96",
  },
  detailContactActions: {
    flexDirection: "row",
    gap: 12,
  },
  detailContactPrimaryButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: "#F37021",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  detailContactPrimaryButtonText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  detailContactSecondaryButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#D7E3F3",
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  detailContactSecondaryButtonText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#17305D",
  },
  detailInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: "#EDF2F7",
  },
  detailInfoLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  detailInfoIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: "#FFF4EC",
    alignItems: "center",
    justifyContent: "center",
  },
  detailInfoLabel: {
    flex: 1,
    fontSize: 14,
    color: "#64748B",
  },
  detailInfoValue: {
    maxWidth: "48%",
    fontSize: 14,
    fontWeight: "700",
    color: "#17305D",
    textAlign: "right",
  },
  detailDescription: {
    fontSize: 14,
    lineHeight: 22,
    color: "#53657D",
  },
  notesGroup: {
    marginTop: 12,
    gap: 10,
  },
  noteRow: {
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    paddingTop: 10,
  },
  noteMeta: {
    fontSize: 12,
    color: "#7C8BA1",
    marginBottom: 4,
  },
  noteContent: {
    fontSize: 14,
    color: "#17305D",
    lineHeight: 20,
  },
});
