import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  appShell: {
    flex: 1,
    backgroundColor: "#F3F6FB",
  },
  loginScreen: {
    flex: 1,
    backgroundColor: "#F3F6FB",
    justifyContent: "center",
    padding: 18,
  },
  loginPanel: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 22,
    gap: 14,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    shadowColor: "#17305D",
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  loginTitle: {
    fontSize: 30,
    fontWeight: "800",
    color: "#17305D",
  },
  loginDescription: {
    fontSize: 15,
    lineHeight: 22,
    color: "#64748B",
  },
  configBanner: {
    borderRadius: 8,
    backgroundColor: "#ecfeff",
    borderWidth: 1,
    borderColor: "#99f6e4",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  configBannerText: {
    fontSize: 12,
    color: "#115e59",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    backgroundColor: "#ffffff",
    gap: 12,
  },
  headerTextGroup: {
    flex: 1,
  },
  headerActions: {
    alignItems: "flex-end",
    gap: 8,
  },
  headerEyebrow: {
    fontSize: 11,
    fontWeight: "700",
    color: "#17305D",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#17305D",
  },
  headerSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: "#7C8BA1",
  },
  userPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#F7F9FC",
    borderWidth: 1,
    borderColor: "#E3EAF3",
  },
  userAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#17305D",
  },
  userAvatarText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
  },
  userPillTextGroup: {
    alignItems: "flex-start",
  },
  userPillName: {
    fontSize: 13,
    fontWeight: "800",
    color: "#17305D",
  },
  userPillRole: {
    fontSize: 12,
    color: "#7C8BA1",
    fontWeight: "600",
  },
  logoutPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
  },
  logoutPillText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#17305D",
  },
  screen: {
    flex: 1,
    backgroundColor: "#F3F6FB",
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 28,
  },
  section: {
    marginBottom: 14,
    padding: 16,
    borderRadius: 24,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
  },
  sectionTitle: {
    marginBottom: 12,
    fontSize: 16,
    fontWeight: "800",
    color: "#17305D",
  },
  fieldBlock: {
    marginBottom: 12,
  },
  fieldLabel: {
    marginBottom: 6,
    fontSize: 13,
    fontWeight: "700",
    color: "#425466",
  },
  input: {
    minHeight: 48,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: "#17305D",
  },
  apiPresetRow: {
    marginTop: 10,
    gap: 10,
  },
  apiPresetButtonPrimary: {
    minHeight: 40,
    alignSelf: "flex-start",
    paddingHorizontal: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#F7F9FC",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  apiPresetButtonPrimaryText: {
    fontSize: 13,
    fontWeight: "800",
    color: "#17305D",
  },
  apiPresetHint: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  apiPresetHintText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 18,
    color: "#7C8BA1",
  },
  searchInput: {
    flex: 1,
    minHeight: 48,
    paddingHorizontal: 0,
    paddingVertical: 10,
    fontSize: 15,
    color: "#17305D",
  },
  searchInputWrap: {
    flex: 1,
    minHeight: 48,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    paddingLeft: 16,
    paddingRight: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  phoneSearchWrap: {
    minHeight: 48,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: "#C7D6F0",
    backgroundColor: "#F4F8FF",
    paddingLeft: 16,
    paddingRight: 14,
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  searchInputIcon: {
    fontSize: 18,
    color: "#7C8BA1",
    marginTop: -1,
  },
  textArea: {
    minHeight: 92,
    textAlignVertical: "top",
  },
  pickerWrap: {
    borderWidth: 1,
    borderColor: "#DCE3EE",
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "#ffffff",
  },
  primaryButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    backgroundColor: "#F37021",
    paddingHorizontal: 16,
  },
  primaryButtonCompact: {
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    backgroundColor: "#F37021",
    paddingHorizontal: 16,
    flexDirection: "row",
    gap: 8,
  },
  primaryButtonCompactWide: {
    flex: 1,
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    backgroundColor: "#F37021",
    paddingHorizontal: 16,
    flexDirection: "row",
    gap: 8,
  },
  primaryButtonInline: {
    flex: 1,
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    backgroundColor: "#F37021",
    paddingHorizontal: 12,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: 15,
  },
  secondaryButton: {
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
  },
  secondaryButtonCompact: {
    flex: 1,
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
  },
  secondaryButtonCompactWide: {
    flex: 1,
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    flexDirection: "row",
    gap: 8,
  },
  secondaryButtonInline: {
    flex: 1,
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
  },
  secondaryButtonText: {
    color: "#17305D",
    fontWeight: "700",
    fontSize: 14,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  tabBar: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 14,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    backgroundColor: "#ffffff",
  },
  tabButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F7F9FC",
    borderWidth: 1,
    borderColor: "#E5ECF4",
  },
  tabButtonIcon: {
    marginBottom: 4,
  },
  tabButtonActive: {
    backgroundColor: "#17305D",
    borderColor: "#17305D",
  },
  tabButtonText: {
    color: "#53657D",
    fontWeight: "700",
    fontSize: 12,
  },
  tabButtonTextActive: {
    color: "#ffffff",
  },
  workspaceContent: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 28,
  },
  workspaceHero: {
    borderRadius: 26,
    padding: 18,
    backgroundColor: "#17305D",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 14,
    marginBottom: 12,
  },
  workspaceHeroIcon: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: "#F37021",
    alignItems: "center",
    justifyContent: "center",
  },
  workspaceHeroText: {
    flex: 1,
  },
  workspaceEyebrow: {
    fontSize: 11,
    fontWeight: "800",
    color: "#F7B58D",
    marginBottom: 5,
  },
  workspaceTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "800",
    color: "#ffffff",
  },
  workspaceDescription: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 19,
    color: "#D7E2F2",
  },
  workspaceStats: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 10,
  },
  workspaceStatCard: {
    flex: 1,
    minHeight: 94,
    borderRadius: 20,
    padding: 14,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
    justifyContent: "center",
  },
  workspaceStatValue: {
    fontSize: 24,
    fontWeight: "800",
    color: "#17305D",
  },
  workspaceStatLabel: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
    color: "#64748B",
  },
  workspaceUserBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "#FFF4EC",
    borderWidth: 1,
    borderColor: "#FED7BA",
    marginBottom: 18,
  },
  workspaceUserText: {
    flex: 1,
  },
  workspaceUserName: {
    fontSize: 14,
    fontWeight: "800",
    color: "#17305D",
  },
  workspaceUserRole: {
    marginTop: 2,
    fontSize: 12,
    color: "#7C5B48",
  },
  workspaceGroup: {
    marginBottom: 20,
  },
  workspaceGroupTitle: {
    marginBottom: 10,
    fontSize: 17,
    fontWeight: "800",
    color: "#17305D",
  },
  workspaceModuleGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  workspaceModuleCard: {
    flexGrow: 1,
    flexBasis: "47%",
    minHeight: 184,
    borderRadius: 22,
    padding: 14,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
  },
  workspaceModuleCardPressed: {
    opacity: 0.72,
  },
  workspaceModuleIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F1F5F9",
    marginBottom: 10,
  },
  workspaceModuleIconReady: {
    backgroundColor: "#FFF1E7",
  },
  workspaceModuleTitle: {
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "800",
    color: "#17305D",
  },
  workspaceModuleDescription: {
    flex: 1,
    marginTop: 5,
    fontSize: 12,
    lineHeight: 17,
    color: "#64748B",
  },
  workspaceModuleFooter: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
  },
  workspaceModuleStatus: {
    flex: 1,
    fontSize: 11,
    fontWeight: "700",
    color: "#94A3B8",
  },
  workspaceModuleStatusReady: {
    color: "#F37021",
  },
  marketListContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 110,
  },
  marketListContentEmpty: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
  },
  marketOverview: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
    borderRadius: 28,
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: 12,
    gap: 12,
  },
  marketOverviewTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  marketOverviewBadge: {
    width: 46,
    height: 46,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EEF3FB",
  },
  marketOverviewTopActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  marketOverviewIconButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
  },
  marketOverviewIconButtonActive: {
    backgroundColor: "#17305D",
    borderColor: "#17305D",
  },
  marketOverviewAddButton: {
    minHeight: 42,
    borderRadius: 14,
    paddingHorizontal: 14,
    backgroundColor: "#F37021",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  marketOverviewAddButtonText: {
    fontSize: 13,
    fontWeight: "800",
    color: "#ffffff",
  },
  marketOverviewTextGroup: {
    gap: 2,
    flex: 1,
  },
  marketOverviewLabel: {
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    color: "#7C8BA1",
  },
  marketOverviewStat: {
    fontSize: 28,
    fontWeight: "800",
    color: "#17305D",
  },
  marketOverviewHint: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 19,
    color: "#7C8BA1",
  },
  searchPanel: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
    borderRadius: 28,
    padding: 12,
    marginBottom: 12,
    gap: 10,
  },
  searchToolbar: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  searchToolbarIconButton: {
    width: 46,
    height: 46,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  toolbarPillRow: {
    flexDirection: "row",
    gap: 10,
  },
  filterChipRow: {
    gap: 8,
    paddingTop: 2,
  },
  filterChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E8EEF5",
    backgroundColor: "#F7F9FC",
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  filterChipText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#425466",
  },
  filterPanel: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
    borderRadius: 24,
    padding: 14,
    marginBottom: 12,
  },
  filterPanelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  filterPanelTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#17305D",
  },
  filterGroupLabel: {
    marginTop: 4,
    marginBottom: 6,
    fontSize: 13,
    fontWeight: "800",
    color: "#17305D",
  },
  filterResetText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#F37021",
  },
  filterRangeRow: {
    flexDirection: "row",
    gap: 10,
  },
  filterRangeField: {
    flex: 1,
  },
  filterButtonRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
  },
  listHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    gap: 12,
  },
  listHeaderTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#17305D",
  },
  listHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  listHeaderCount: {
    fontSize: 13,
    fontWeight: "700",
    color: "#7C8BA1",
    backgroundColor: "#EEF3FB",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  listContainer: {
    paddingBottom: 20,
  },
  emptyListContainer: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  emptyStateText: {
    color: "#64748B",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },
  propertyRow: {
    marginBottom: 14,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    overflow: "hidden",
    shadowColor: "#17305D",
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  createFab: {
    position: "absolute",
    right: 16,
    bottom: 18,
    minHeight: 54,
    borderRadius: 20,
    paddingHorizontal: 18,
    backgroundColor: "#F37021",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    shadowColor: "#F37021",
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  createFabText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "800",
  },
  propertyCardTapArea: {
    overflow: "hidden",
  },
  propertyHero: {
    minHeight: 168,
    backgroundColor: "#E7EEF8",
    padding: 16,
    justifyContent: "space-between",
  },
  propertyHeroTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  propertyHeroStatus: {
    backgroundColor: "#ffffff",
  },
  propertyHeroTopActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  propertyCodePill: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  propertyCode: {
    fontSize: 13,
    fontWeight: "800",
    color: "#17305D",
  },
  propertyHeroBody: {
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 8,
  },
  propertyHeroIconWrap: {
    width: 82,
    height: 82,
    borderRadius: 26,
    backgroundColor: "#F9FBFE",
    alignItems: "center",
    justifyContent: "center",
  },
  propertyFavoriteBubble: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E4ECF6",
  },
  propertyHeroLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "#8B9AB0",
  },
  propCard: {
    backgroundColor: "#ffffff",
    marginHorizontal: 12,
    marginVertical: 4,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: "#E4ECF6",
    gap: 5,
    elevation: 2,
    shadowColor: "#17305D",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 3,
  },
  propCardRow1: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  propCardPrice: {
    fontSize: 18,
    fontWeight: "700",
    color: "#F37021",
    letterSpacing: -0.3,
  },
  propCardDims: {
    fontSize: 13,
    color: "#6B7FA3",
    fontWeight: "500",
    flex: 1,
  },
  propCardBadge: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 9,
    paddingVertical: 3,
  },
  propCardBadgeText: {
    fontSize: 11,
    fontWeight: "700",
  },
  propCardAddress: {
    fontSize: 14,
    fontWeight: "600",
    color: "#17305D",
    lineHeight: 20,
  },
  propCardContactRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 1,
  },
  propCardContact: {
    flex: 1,
    fontSize: 13,
    color: "#6B7FA3",
  },
  propCardDateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 1,
  },
  propCardDate: {
    fontSize: 12,
    color: "#94A3B8",
  },
  propCardPhoneBtn: {
    padding: 2,
  },
  compactCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: "#ffffff",
    marginHorizontal: 10,
    marginVertical: 3,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#E4ECF6",
    elevation: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  compactCardBody: {
    flex: 1,
    gap: 3,
  },
  compactCardMain: {
    fontSize: 14,
    fontWeight: "600",
    color: "#17305D",
    lineHeight: 20,
  },
  compactCardContactRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  compactCardContact: {
    flex: 1,
    fontSize: 13,
    color: "#4A6280",
  },
  compactCardPhoneBtn: {
    padding: 2,
  },
  propertyHeroContact: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "rgba(255,255,255,0.55)",
    borderTopWidth: 1,
    borderTopColor: "#D4E2F4",
  },
  propertyHeroContactBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#17305D",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  propertyHeroContactInitials: {
    fontSize: 13,
    fontWeight: "700",
    color: "#ffffff",
  },
  propertyHeroContactInfo: {
    flex: 1,
    gap: 2,
  },
  propertyHeroContactName: {
    fontSize: 13,
    fontWeight: "700",
    color: "#17305D",
  },
  propertyHeroContactPhone: {
    fontSize: 12,
    color: "#4A6280",
  },
  propertyHeroContactPhoneMissing: {
    fontSize: 12,
    color: "#A0AEC0",
    fontStyle: "italic",
  },
  propertyHeroPhoneButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#FFF1E7",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  statusBadge: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: "700",
  },
  propertyBody: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 14,
  },
  propertyPriceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 8,
  },
  propertyUpdatedChip: {
    borderRadius: 999,
    backgroundColor: "#FFF1E7",
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  propertyUpdatedChipText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#F37021",
  },
  propertyTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#17305D",
    lineHeight: 25,
    marginBottom: 6,
  },
  propertyLocation: {
    fontSize: 14,
    color: "#53657D",
    marginBottom: 8,
  },
  propertyPrice: {
    flex: 1,
    fontSize: 30,
    fontWeight: "800",
    color: "#17305D",
  },
  propertyFactsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 10,
  },
  propertyFact: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    backgroundColor: "#F7F9FC",
    borderWidth: 1,
    borderColor: "#E5ECF4",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  propertyFactText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#5A6A82",
  },
  propertyAddressPrimary: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: "800",
    color: "#17305D",
    marginBottom: 2,
  },
  propertyAddressSecondary: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
    color: "#7C8BA1",
    marginBottom: 8,
  },
  propertySnippet: {
    fontSize: 13,
    lineHeight: 20,
    color: "#53657D",
    marginBottom: 12,
  },
  propertyActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  propertyActionBar: {
    paddingHorizontal: 16,
    paddingBottom: 14,
    marginTop: -2,
  },
  propertyPrimaryAction: {
    flex: 1,
    minHeight: 46,
    borderRadius: 18,
    backgroundColor: "#F37021",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  propertyPrimaryActionText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#ffffff",
  },
  propertySecondaryAction: {
    flex: 1,
    minHeight: 46,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#F8FBFF",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  propertySecondaryActionText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#17305D",
  },
  listRow: {
    marginBottom: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#dbe3ef",
    backgroundColor: "#ffffff",
    padding: 14,
  },
  listRowTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  listRowCode: {
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
    color: "#0f766e",
  },
  listRowStatus: {
    fontSize: 12,
    color: "#475569",
  },
  listRowTitle: {
    marginTop: 4,
    fontSize: 16,
    fontWeight: "700",
    color: "#0f172a",
  },
  listRowMeta: {
    marginTop: 4,
    fontSize: 13,
    color: "#475569",
  },
  listRowDescription: {
    marginTop: 6,
    fontSize: 13,
    color: "#64748b",
  },
  screenCenter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F3F6FB",
    padding: 20,
    gap: 12,
  },
  bootText: {
    color: "#53657D",
  },
  detailTopBar: {
    marginTop: 4,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  detailNavButton: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    minHeight: 42,
    paddingHorizontal: 14,
    borderRadius: 16,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
  },
  detailNavButtonText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#17305D",
  },
  detailTopBarActions: {
    flexDirection: "row",
    gap: 8,
  },
  detailTopIconButton: {
    width: 42,
    height: 42,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  detailDeleteButton: {
    width: 42,
    height: 42,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#F5B7B1",
    backgroundColor: "#FDEDEC",
    alignItems: "center",
    justifyContent: "center",
  },
  detailTopIconButtonPrimary: {
    width: 42,
    height: 42,
    borderRadius: 16,
    backgroundColor: "#F37021",
    alignItems: "center",
    justifyContent: "center",
  },
  detailHeroCard: {
    marginBottom: 0,
    borderRadius: 28,
    padding: 16,
    backgroundColor: "#E7EEF8",
    borderWidth: 1,
    borderColor: "#D8E3F3",
  },
  detailHeroTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    marginBottom: 22,
  },
  detailHeroMedia: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 170,
    gap: 12,
  },
  detailHeroMediaIconWrap: {
    width: 96,
    height: 96,
    borderRadius: 30,
    backgroundColor: "#F9FBFE",
    alignItems: "center",
    justifyContent: "center",
  },
  detailHeroMediaLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: "#8B9AB0",
  },
  detailSummaryCard: {
    marginTop: -28,
    marginBottom: 14,
    marginHorizontal: 8,
    padding: 16,
    borderRadius: 24,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
    shadowColor: "#17305D",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  formHeroCard: {
    marginBottom: 14,
    borderRadius: 24,
    padding: 18,
    backgroundColor: "#EAF1FB",
    borderWidth: 1,
    borderColor: "#D8E3F3",
  },
  formHeroEyebrow: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0,
    color: "#7C8BA1",
    marginBottom: 8,
  },
  formHeroTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#17305D",
    lineHeight: 28,
  },
  formHeroDescription: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 21,
    color: "#53657D",
  },
  formHeroChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 14,
  },
  formHeroChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
  },
  formHeroChipDone: {
    backgroundColor: "#ECFDF5",
    borderColor: "#A7F3D0",
  },
  formHeroChipPending: {
    backgroundColor: "#FFF7ED",
    borderColor: "#FED7AA",
  },
  formHeroChipText: {
    fontSize: 12,
    fontWeight: "700",
  },
  formHeroChipTextDone: {
    color: "#047857",
  },
  formHeroChipTextPending: {
    color: "#C2410C",
  },
  backButton: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 8,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
  },
  detailHeroMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: 12,
    marginBottom: 12,
  },
  detailPrice: {
    flex: 1,
    fontSize: 28,
    fontWeight: "800",
    color: "#17305D",
  },
  detailArea: {
    fontSize: 16,
    fontWeight: "700",
    color: "#53657D",
  },
  detailChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 14,
  },
  detailChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E5ECF4",
    backgroundColor: "#F8FAFD",
  },
  detailChipText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#425466",
  },
  detailTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#17305D",
    lineHeight: 32,
    marginBottom: 6,
  },
  detailLocation: {
    fontSize: 14,
    color: "#64748B",
    marginBottom: 12,
  },
  detailAddressPrimary: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: "800",
    color: "#17305D",
    marginTop: 4,
    marginBottom: 2,
  },
  detailAddressSecondary: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
    color: "#6B7D96",
    marginBottom: 6,
  },
  detailActionRow: {
    flexDirection: "row",
    gap: 10,
  },
  detailActionPrimary: {
    flex: 1,
    minHeight: 46,
    borderRadius: 18,
    backgroundColor: "#F37021",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  detailActionPrimaryText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#ffffff",
  },
  detailActionSecondary: {
    flex: 1,
    minHeight: 46,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  detailActionSecondaryText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#17305D",
  },
  detailContactCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#D9E4F2",
    padding: 20,
    gap: 16,
    shadowColor: "#17305D",
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  detailContactHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  detailContactBadge: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#FFF3EB",
    alignItems: "center",
    justifyContent: "center",
  },
  detailContactHeaderText: {
    flex: 1,
    gap: 2,
  },
  detailContactEyebrow: {
    fontSize: 12,
    fontWeight: "700",
    color: "#F37021",
    textTransform: "uppercase",
  },
  detailContactOwner: {
    fontSize: 17,
    fontWeight: "700",
    color: "#17305D",
  },
  detailContactNumberWrap: {
    borderRadius: 22,
    backgroundColor: "#F8FBFF",
    borderWidth: 1,
    borderColor: "#D7E3F3",
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 6,
  },
  detailContactNumber: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "800",
    color: "#0F172A",
  },
  detailContactHint: {
    fontSize: 13,
    lineHeight: 18,
    color: "#6B7D96",
  },
  detailContactActions: {
    flexDirection: "row",
    gap: 12,
  },
  detailContactPrimaryButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: "#F37021",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  detailContactPrimaryButtonText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  detailContactSecondaryButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#D7E3F3",
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  detailContactSecondaryButtonText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#17305D",
  },
  detailInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: "#EDF2F7",
  },
  detailInfoLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  detailInfoIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: "#FFF4EC",
    alignItems: "center",
    justifyContent: "center",
  },
  detailInfoLabel: {
    flex: 1,
    fontSize: 14,
    color: "#64748B",
  },
  detailInfoValue: {
    maxWidth: "48%",
    fontSize: 14,
    fontWeight: "700",
    color: "#17305D",
    textAlign: "right",
  },
  detailDescription: {
    fontSize: 14,
    lineHeight: 22,
    color: "#53657D",
  },
  notesGroup: {
    marginTop: 12,
    gap: 10,
  },
  noteRow: {
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    paddingTop: 10,
  },
  noteMeta: {
    fontSize: 12,
    color: "#7C8BA1",
    marginBottom: 4,
  },
  noteContent: {
    fontSize: 14,
    color: "#17305D",
    lineHeight: 20,
  },
  draftHint: {
    marginBottom: 12,
  },
  draftHintText: {
    fontSize: 12,
    color: "#7C8BA1",
  },
  submitPanel: {
    marginBottom: 18,
    padding: 16,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    gap: 8,
  },
  submitPanelTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#17305D",
  },
  submitPanelDescription: {
    fontSize: 13,
    lineHeight: 20,
    color: "#64748B",
    marginBottom: 4,
  },
  activityListContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
  },
  activityListEmpty: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
  },
  activityHeroCard: {
    marginBottom: 14,
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
  },
  activityHeroStatsRow: {
    marginTop: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  activityHeroStat: {
    flex: 1,
    minHeight: 82,
    borderRadius: 20,
    backgroundColor: "#F7F9FC",
    borderWidth: 1,
    borderColor: "#E6EDF5",
    paddingHorizontal: 14,
    paddingVertical: 12,
    justifyContent: "center",
  },
  activityHeroStatValue: {
    fontSize: 24,
    fontWeight: "800",
    color: "#17305D",
  },
  activityHeroStatLabel: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: "700",
    color: "#7C8BA1",
  },
  activityRow: {
    marginBottom: 10,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#ffffff",
    padding: 16,
  },
  activityRowTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 6,
  },
  activityBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  activityBadgeText: {
    fontSize: 12,
    fontWeight: "800",
  },
  activityAction: {
    fontSize: 14,
    fontWeight: "800",
    color: "#17305D",
    flex: 1,
  },
  activityMeta: {
    fontSize: 13,
    color: "#7C8BA1",
    lineHeight: 20,
  },
  activityResult: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 21,
    color: "#425466",
  },
  // listing type toggle
  listingTypeRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  listingTypeButton: {
    flex: 1,
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    backgroundColor: "#F7F9FC",
  },
  listingTypeButtonActive: {
    backgroundColor: "#17305D",
    borderColor: "#17305D",
  },
  listingTypeButtonText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#53657D",
  },
  listingTypeButtonTextActive: {
    color: "#ffffff",
  },
  createReadyRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexWrap: "wrap",
  },
  createReadyChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: "#F1F5F9",
    borderWidth: 1,
    borderColor: "#CBD5E1",
  },
  createReadyChipDone: {
    backgroundColor: "#DCFCE7",
    borderColor: "#86EFAC",
  },
  createReadyChipText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#94A3B8",
  },
  createReadyChipTextDone: {
    color: "#16A34A",
  },
  createSavingText: {
    fontSize: 12,
    color: "#94A3B8",
    marginLeft: "auto",
  },
  createDimsRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
  },
  createDimsField: {
    flex: 1,
  },
  createDimsSep: {
    fontSize: 18,
    color: "#94A3B8",
    paddingBottom: 10,
    fontWeight: "500",
  },
  listFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 18,
  },
  listFooterText: {
    fontSize: 13,
    color: "#8B9AB0",
  },
  loadMoreButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#F3702155",
    backgroundColor: "#FFF3EC",
  },
  loadMoreButtonText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#F37021",
  },
  rangeSliderTrackWrap: {
    height: 44,
    justifyContent: "center",
    position: "relative",
    marginTop: 6,
    marginBottom: 2,
  },
  rangeSliderTrack: {
    position: "absolute",
    left: 13,
    right: 13,
    top: 19.5,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#E2E8F0",
  },
  rangeSliderActive: {
    position: "absolute",
    top: 19.5,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#F37021",
  },
  rangeSliderThumb: {
    position: "absolute",
    top: 9,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "#ffffff",
    borderWidth: 2,
    borderColor: "#F37021",
    elevation: 3,
    shadowColor: "#17305D",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  rangeValueLabel: {
    fontSize: 13,
    color: "#6B7FA3",
    textAlign: "right",
    marginTop: 2,
  },
  quickChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  quickChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#D9E2EC",
    backgroundColor: "#ffffff",
  },
  quickChipActive: {
    borderColor: "#F37021",
    backgroundColor: "#FFF3EC",
  },
  quickChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#53657D",
  },
  quickChipTextActive: {
    color: "#F37021",
  },
  typeToggleRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 6,
  },
  typeToggleButton: {
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#D9E2EC",
    backgroundColor: "#ffffff",
  },
  typeToggleButtonActive: {
    borderColor: "#F37021",
    backgroundColor: "#FFF3EC",
  },
  typeToggleText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#53657D",
  },
  typeToggleTextActive: {
    color: "#F37021",
  },
  lsFormTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#17305D",
    paddingHorizontal: 16,
    marginTop: 4,
  },
  lsFormSubtitle: {
    fontSize: 13,
    color: "#6B7FA3",
    paddingHorizontal: 16,
    marginTop: 2,
    marginBottom: 4,
  },
  chototPasteButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 2,
    minHeight: 46,
    borderRadius: 18,
    backgroundColor: "#15428B",
  },
  chototPasteButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  chototPasteHint: {
    fontSize: 11.5,
    color: "#8CA0C3",
    paddingHorizontal: 16,
    marginBottom: 6,
  },
  menuButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EDF1F9",
    marginRight: 10,
  },
  headerCompact: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    backgroundColor: "#ffffff",
  },
  headerCompactTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#17305D",
  },
  drawerBackdrop: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "rgba(10, 22, 44, 0.45)",
  },
  drawerPanel: {
    width: 292,
    height: "100%",
    backgroundColor: "#FFFFFF",
    paddingTop: 46,
    borderTopRightRadius: 18,
    borderBottomRightRadius: 18,
  },
  drawerHeader: {
    paddingHorizontal: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#E4EAF5",
  },
  drawerBrand: {
    fontSize: 12,
    fontWeight: "800",
    color: "#F37021",
    letterSpacing: 1,
  },
  drawerUser: {
    fontSize: 16,
    fontWeight: "800",
    color: "#17305D",
    marginTop: 4,
  },
  drawerRole: {
    fontSize: 12,
    color: "#6B7FA3",
    marginTop: 2,
  },
  drawerItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 13,
    paddingHorizontal: 18,
  },
  drawerItemActive: {
    backgroundColor: "#EDF3FF",
    borderRightWidth: 3,
    borderRightColor: "#15428B",
  },
  drawerItemText: {
    fontSize: 15,
    color: "#2A3A55",
    fontWeight: "600",
  },
  drawerItemTextActive: {
    color: "#15428B",
    fontWeight: "800",
  },
  drawerLogout: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 15,
    paddingHorizontal: 18,
    borderTopWidth: 1,
    borderTopColor: "#E4EAF5",
    marginTop: "auto",
    marginBottom: 18,
  },
  wfScreen: {
    backgroundColor: "#ECEEF1",
  },
  wfGroup: {
    marginHorizontal: 8,
    marginTop: 10,
    paddingHorizontal: 8,
    paddingTop: 6,
    paddingBottom: 8,
    borderWidth: 1,
    borderColor: "#B9C0CB",
    borderRadius: 3,
    backgroundColor: "#F4F5F7",
  },
  wfGroupTitle: {
    fontSize: 13.5,
    fontWeight: "700",
    color: "#1F3B70",
    marginBottom: 4,
  },
  wfRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 5,
    minHeight: 34,
  },
  wfLabel: {
    width: 112,
    fontSize: 12.5,
    color: "#222B3A",
  },
  wfControl: {
    flex: 1,
  },
  wfDimRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 5,
  },
  wfDimCell: {
    flex: 1,
  },
  wfDimLabel: {
    fontSize: 12.5,
    color: "#222B3A",
    marginBottom: 4,
  },
  wfInput: {
    borderWidth: 1,
    borderColor: "#A8B0BC",
    borderRadius: 2,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 8,
    paddingVertical: 6,
    fontSize: 13.5,
    color: "#111827",
    minHeight: 34,
  },
  wfInputDisabled: {
    backgroundColor: "#E8EAED",
    color: "#5B6472",
  },
  wfInputRequiredPhone: {
    backgroundColor: "#FFD2D2",
  },
  wfInputDone: {
    backgroundColor: "#E9F7EC",
    borderColor: "#8FCF9F",
  },
  wfPickerWrapDone: {
    backgroundColor: "#E9F7EC",
    borderColor: "#8FCF9F",
  },
  wfPickerWrap: {
    borderWidth: 1,
    borderColor: "#A8B0BC",
    borderRadius: 2,
    backgroundColor: "#FFFFFF",
    height: 44,
    justifyContent: "center",
    overflow: "hidden",
  },
  wfRadioRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  wfRadioItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  wfRadioOuter: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#5B6472",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  wfRadioInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#1F5FBF",
  },
  wfRadioText: {
    fontSize: 13,
    color: "#111827",
  },
  wfCheckRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    flexWrap: "wrap",
  },
  wfCheckItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  wfCheckBox: {
    width: 15,
    height: 15,
    borderWidth: 1.2,
    borderColor: "#5B6472",
    borderRadius: 2,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  wfCheckBoxChecked: {
    backgroundColor: "#1F5FBF",
    borderColor: "#1F5FBF",
  },
  wfCheckText: {
    fontSize: 13,
    color: "#111827",
  },
  wfBtnRow: {
    flexDirection: "row",
    gap: 8,
    marginHorizontal: 8,
    marginTop: 12,
  },
  wfBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 40,
    borderWidth: 1,
    borderColor: "#8F98A6",
    borderRadius: 3,
    backgroundColor: "#F7F8FA",
  },
  wfBtnPrimary: {
    backgroundColor: "#DEE9F8",
    borderColor: "#4A7BC8",
  },
  wfBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1F3B70",
  },
  wfThuongLuong: {
    color: "#D00000",
    fontSize: 13,
    fontWeight: "800",
  },
  wfHint: {
    fontSize: 11.5,
    color: "#6B7280",
    marginTop: 2,
  },
  lsThuongLuongLabel: {
    color: "#D32F2F",
    fontSize: 13.5,
    fontWeight: "800",
    marginTop: 6,
  },
  chototPickerBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15, 30, 60, 0.55)",
    justifyContent: "flex-end",
  },
  chototPickerSheet: {
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingTop: 16,
    paddingBottom: 24,
    paddingHorizontal: 16,
    maxHeight: "75%",
  },
  chototPickerHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  chototPickerTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#17305D",
  },
  chototPickerList: {
    flexGrow: 0,
  },
  chototPickerItem: {
    borderWidth: 1,
    borderColor: "#DCE4F2",
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 10,
    backgroundColor: "#F8FAFE",
  },
  chototPickerItemPressed: {
    backgroundColor: "#E8F0FE",
    borderColor: "#15428B",
  },
  chototPickerItemTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#17305D",
  },
  chototPickerItemSub: {
    fontSize: 12.5,
    color: "#6B7FA3",
    marginTop: 3,
  },
  chototPickerCancel: {
    marginTop: 6,
    minHeight: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EDF1F9",
  },
  chototPickerCancelText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#17305D",
  },
  khSearchWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginHorizontal: 16,
    marginTop: 12,
    paddingHorizontal: 12,
    minHeight: 46,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#DCE4F2",
    backgroundColor: "#ffffff",
  },
  khSearchInput: {
    flex: 1,
    fontSize: 14.5,
    color: "#17305D",
    paddingVertical: 10,
  },
  khTotal: {
    fontSize: 12,
    color: "#8CA0C3",
    paddingHorizontal: 16,
    marginTop: 6,
    marginBottom: 8,
  },
  khCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginHorizontal: 16,
    marginBottom: 8,
    paddingVertical: 11,
    paddingHorizontal: 12,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#E4EAF5",
    backgroundColor: "#ffffff",
  },
  khAvatarSmall: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#15428B",
  },
  khAvatarText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "800",
  },
  khName: {
    fontSize: 14.5,
    fontWeight: "700",
    color: "#17305D",
  },
  khMeta: {
    fontSize: 12,
    color: "#6B7FA3",
    marginTop: 2,
  },
  khBadge: {
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: "#FDEAD9",
  },
  khBadgeText: {
    fontSize: 11.5,
    fontWeight: "700",
    color: "#F37021",
  },
  khBackRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  khBackText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#15428B",
  },
  khDetailHero: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginHorizontal: 16,
    marginBottom: 10,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#E4EAF5",
  },
  khAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#15428B",
  },
  khDetailName: {
    fontSize: 17,
    fontWeight: "800",
    color: "#17305D",
  },
  khPhoneRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginHorizontal: 16,
    marginBottom: 8,
    paddingHorizontal: 14,
    minHeight: 46,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#FBD8B9",
    backgroundColor: "#FFF7F0",
  },
  khPhoneText: {
    flex: 1,
    fontSize: 15,
    fontWeight: "800",
    color: "#17305D",
  },
  khPhoneHint: {
    fontSize: 11,
    color: "#B9822F",
  },
  khInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginHorizontal: 16,
    marginBottom: 6,
  },
  khInfoText: {
    flex: 1,
    fontSize: 13,
    color: "#44536E",
  },
  khNoteBox: {
    marginHorizontal: 16,
    marginBottom: 8,
    padding: 12,
    borderRadius: 14,
    backgroundColor: "#F4F7FC",
  },
  khNoteText: {
    fontSize: 13,
    color: "#44536E",
  },
  khSectionTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#17305D",
    paddingHorizontal: 16,
    marginTop: 14,
    marginBottom: 8,
  },
  khEmpty: {
    fontSize: 13,
    color: "#8CA0C3",
    paddingHorizontal: 16,
  },
  khPropCard: {
    marginHorizontal: 16,
    marginBottom: 8,
    padding: 12,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#E4EAF5",
    backgroundColor: "#ffffff",
  },
  khPropTitle: {
    fontSize: 13.5,
    fontWeight: "700",
    color: "#17305D",
  },
  lsGiaQuyDoi: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1565C0",
    marginTop: 4,
  },
  inputDuplicate: {
    borderColor: "#DC2626",
    borderWidth: 1.5,
    backgroundColor: "#FFE4E4",
  },
  lsPhoneDupWarn: {
    fontSize: 12,
    fontWeight: "700",
    color: "#DC2626",
    marginTop: 4,
  },
  lsPhoneStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  lsPhoneChecking: {
    fontSize: 12,
    color: "#6B7FA3",
  },
  lsPhoneOk: {
    fontSize: 12,
    fontWeight: "600",
    color: "#16A34A",
    marginTop: 4,
  },
  lsPhoneOwnerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 3,
  },
  lsPhoneOwner: {
    fontSize: 12,
    fontWeight: "600",
    color: "#15428B",
  },
  lsStreetDropdown: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#C5CEE0",
    borderRadius: 10,
    marginTop: 4,
    overflow: "hidden",
  },
  lsStreetItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 11,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#EEF1F6",
  },
  lsStreetItemText: {
    fontSize: 14,
    color: "#17305D",
  },
  lsStreetHint: {
    fontSize: 11,
    color: "#94A3B8",
    marginTop: 3,
  },
  lsGridRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  lsGridCell: {
    flexGrow: 1,
    flexBasis: "47%",
  },
  lsCellLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#53657D",
    marginBottom: 5,
  },
  lsCheckGroup: {
    flexDirection: "row",
    gap: 18,
    marginTop: 4,
  },
  lsCheckRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 6,
  },
  lsCheckBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: "#B6C2D4",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  lsCheckBoxOn: {
    backgroundColor: "#F37021",
    borderColor: "#F37021",
  },
  lsCheckLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: "#17305D",
  },
  lsOpenFullButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 4,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#F3702155",
    backgroundColor: "#FFF3EC",
  },
  lsOpenFullTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#F37021",
  },
  lsOpenFullDesc: {
    fontSize: 12,
    color: "#9A6B4F",
    marginTop: 1,
  },
  callLogListContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 96,
  },
  callLogHeroCard: {
    padding: 18,
    borderRadius: 20,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
    marginBottom: 12,
    shadowColor: "#0F172A",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  callLogHeroTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  callLogBellButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  callLogBellButtonOn: {
    backgroundColor: "#F37021",
    borderColor: "#F37021",
    shadowColor: "#F37021",
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  callLogStatsRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 16,
  },
  callLogPanel: {
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
    marginBottom: 12,
    shadowColor: "#0F172A",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  callLogToolbar: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  callLogEmployeeList: {
    marginTop: 10,
    gap: 8,
  },
  callLogEmployeeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#F8FAFC",
  },
  callLogEmployeeRowSelected: {
    borderColor: "#F37021",
    backgroundColor: "#FFF7ED",
  },
  callLogEmployeeAvatar: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#17305D",
    alignItems: "center",
    justifyContent: "center",
  },
  callLogEmployeeAvatarActive: {
    backgroundColor: "#F37021",
  },
  callLogEmployeeAvatarText: {
    fontSize: 13,
    fontWeight: "900",
    color: "#ffffff",
  },
  callLogEmployeeMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  callLogEmployeeTextWrap: {
    flex: 1,
  },
  callLogEmployeeName: {
    fontSize: 14,
    fontWeight: "800",
    color: "#17305D",
  },
  callLogEmployeeMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  callLogEmployeeCountBadge: {
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: "#E2E8F0",
  },
  callLogEmployeeCountBadgeActive: {
    backgroundColor: "#FFE4CC",
  },
  callLogEmployeeCountBadgeText: {
    fontSize: 11,
    fontWeight: "900",
    color: "#64748B",
  },
  callLogEmployeeCountBadgeTextActive: {
    color: "#B54708",
  },
  callLogEmployeeMeta: {
    fontSize: 12,
    color: "#64748B",
  },
  callLogWatchButton: {
    width: 36,
    height: 36,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  callLogWatchButtonOn: {
    backgroundColor: "#15428B",
    borderColor: "#15428B",
    shadowColor: "#15428B",
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  callLogHint: {
    marginTop: 8,
    fontSize: 12,
    color: "#64748B",
  },
  callLogPresetRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 8,
  },
  callLogPresetButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#ffffff",
  },
  callLogPresetButtonOn: {
    backgroundColor: "#17305D",
    borderColor: "#17305D",
  },
  callLogPresetText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#475569",
  },
  callLogPresetTextOn: {
    color: "#ffffff",
  },
  callLogCalendarButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#F37021",
    backgroundColor: "#ffffff",
  },
  callLogCalendarButtonOn: {
    backgroundColor: "#F37021",
    borderColor: "#F37021",
  },
  callLogDayHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 6,
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  callLogDayHeaderText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#17305D",
  },
  callLogDayHeaderCount: {
    fontSize: 12,
    fontWeight: "700",
    color: "#F37021",
  },
  callLogCollapseHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 4,
  },
  callLogCollapseTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#17305D",
  },
  callLogCollapseSummary: {
    fontSize: 12,
    color: "#64748B",
    marginTop: 2,
  },
  callLogChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 8,
  },
  callLogChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "#EDF3FF",
    borderWidth: 1,
    borderColor: "#BFD3F2",
  },
  callLogChipText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#15428B",
  },
  calOverlay: {
    flex: 1,
    backgroundColor: "rgba(10, 22, 44, 0.5)",
    justifyContent: "center",
    padding: 20,
  },
  calSheet: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 16,
  },
  calHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  calMonthTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#17305D",
  },
  calNavButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EDF1F9",
  },
  calWeekRow: {
    flexDirection: "row",
    marginBottom: 4,
  },
  calWeekDayText: {
    flex: 1,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "800",
    color: "#64748B",
  },
  calDayCell: {
    flex: 1,
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    margin: 1,
  },
  calDayInRange: {
    backgroundColor: "#FDE7D8",
  },
  calDaySelected: {
    backgroundColor: "#F37021",
  },
  calDayText: {
    fontSize: 14,
    color: "#17305D",
  },
  calDayTextMuted: {
    color: "#C2CBD9",
  },
  calDayTextSelected: {
    color: "#ffffff",
    fontWeight: "800",
  },
  calRangeText: {
    textAlign: "center",
    fontSize: 13,
    fontWeight: "700",
    color: "#17305D",
    marginVertical: 10,
  },
  calFooterRow: {
    flexDirection: "row",
    gap: 10,
  },
  calCancelButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#ffffff",
  },
  calCancelText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#475569",
  },
  calApplyButton: {
    flex: 2,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#F37021",
  },
  calApplyText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#ffffff",
  },
  callLogRow: {
    padding: 14,
    borderRadius: 16,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE3EE",
    marginBottom: 10,
    shadowColor: "#0F172A",
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  callLogRowTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  callLogStaffBadge: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "#EEF2FF",
  },
  callLogStaffBadgeText: {
    fontSize: 11,
    fontWeight: "900",
    color: "#15428B",
  },
  callLogTime: {
    flex: 1,
    textAlign: "right",
    fontSize: 12,
    color: "#64748B",
  },
  callLogStaffName: {
    marginTop: 8,
    fontSize: 15,
    fontWeight: "800",
    color: "#17305D",
  },
  callLogAddress: {
    marginTop: 5,
    fontSize: 15,
    fontWeight: "700",
    color: "#334155",
  },
  callLogMeta: {
    marginTop: 5,
    fontSize: 13,
    lineHeight: 19,
    color: "#64748B",
  },
  callLogPhoneRow: {
    marginTop: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  callLogPhone: {
    flex: 1,
    fontSize: 15,
    fontWeight: "900",
    color: "#F37021",
  },
  callLogDetailOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(15, 23, 42, 0.42)",
  },
  callLogDetailSheet: {
    maxHeight: "86%",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 20,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    backgroundColor: "#F8FBFF",
  },
  callLogDetailHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  callLogDetailTitleWrap: {
    flex: 1,
  },
  callLogDetailTitle: {
    marginTop: 4,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "900",
    color: "#17305D",
  },
  callLogDetailSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: "#64748B",
  },
  callLogDetailCloseButton: {
    width: 42,
    height: 42,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#DCE3EE",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  callLogDetailLoading: {
    minHeight: 220,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  callLogDetailListContent: {
    paddingBottom: 16,
  },
  // ===== King Land desktop-style grid =====
  klRoot: {
    flex: 1,
    backgroundColor: "#EDEFF2",
  },
  klTitleBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#2B2F36",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  klTitleText: {
    color: "#E8EAED",
    fontSize: 11,
    fontWeight: "600",
    flex: 1,
  },
  klMenuBar: {
    backgroundColor: "#F4F5F7",
    borderBottomWidth: 1,
    borderBottomColor: "#C9CED6",
    flexGrow: 0,
  },
  klMenuItem: {
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  klMenuText: {
    fontSize: 10.5,
    fontWeight: "700",
    color: "#2A3646",
  },
  klTabStrip: {
    flexDirection: "row",
    backgroundColor: "#E3E6EB",
    paddingTop: 4,
    paddingHorizontal: 6,
    gap: 4,
  },
  klTabActive: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: "#C9CED6",
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  klTabInactive: {
    backgroundColor: "#D6DAE1",
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  klTabText: {
    fontSize: 10.5,
    fontWeight: "800",
    color: "#17305D",
  },
  klTabTextInactive: {
    fontSize: 10.5,
    fontWeight: "700",
    color: "#5B6572",
  },
  klFilterBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#D5DAE1",
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  klStatusPickerWrap: {
    flex: 1.2,
    borderWidth: 1,
    borderColor: "#C9CED6",
    borderRadius: 4,
    height: 38,
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  klStatusPicker: {
    marginVertical: -8,
  },
  klSearchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#C9CED6",
    borderRadius: 4,
    height: 38,
    paddingHorizontal: 8,
    fontSize: 12,
    backgroundColor: "#FFFFFF",
  },
  klFilterButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderWidth: 1,
    borderColor: "#B9C2CF",
    borderRadius: 4,
    paddingHorizontal: 10,
    height: 38,
    backgroundColor: "#F4F5F7",
  },
  klFilterButtonText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#17305D",
  },
  klToolbar: {
    backgroundColor: "#F8F9FA",
    borderBottomWidth: 1,
    borderBottomColor: "#D5DAE1",
    flexGrow: 0,
  },
  klToolButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 7,
    borderRightWidth: 1,
    borderRightColor: "#E3E6EB",
  },
  klToolButtonText: {
    fontSize: 10.5,
    fontWeight: "600",
    color: "#2A3646",
  },
  klGridArea: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  klHeaderRow: {
    flexDirection: "row",
    backgroundColor: "#E9ECF1",
    borderBottomWidth: 1,
    borderBottomColor: "#B9C2CF",
  },
  klHeaderCell: {
    fontSize: 10,
    fontWeight: "800",
    color: "#2A3646",
    paddingHorizontal: 5,
    paddingVertical: 7,
    borderRightWidth: 1,
    borderRightColor: "#D5DAE1",
  },
  klRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#EDEFF2",
    backgroundColor: "#FFFFFF",
  },
  klRowAlt: {
    backgroundColor: "#F7F9FB",
  },
  klRowSelected: {
    backgroundColor: "#D8E6FA",
  },
  klCell: {
    fontSize: 10.5,
    color: "#232B36",
    paddingHorizontal: 5,
    paddingVertical: 8,
    borderRightWidth: 1,
    borderRightColor: "#F0F2F5",
  },
  klCellPrice: {
    fontWeight: "800",
    color: "#17305D",
  },
  klLoadingWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 14,
  },
  klLoadingText: {
    fontSize: 11.5,
    color: "#5B6572",
  },
  klFooterBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F4F5F7",
    borderTopWidth: 1,
    borderTopColor: "#C9CED6",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  klCountBox: {
    borderWidth: 1,
    borderColor: "#B9C2CF",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 3,
  },
  klCountText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#17305D",
  },
  klFooterHint: {
    fontSize: 10.5,
    color: "#5B6572",
  },
  klDetailPanel: {
    maxHeight: 230,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#B9C2CF",
  },
  klDetailTabs: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E9ECF1",
    borderBottomWidth: 1,
    borderBottomColor: "#C9CED6",
  },
  klDetailTab: {
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  klDetailTabActive: {
    backgroundColor: "#FFFFFF",
    borderTopWidth: 2,
    borderTopColor: "#F37021",
  },
  klDetailTabText: {
    fontSize: 10.5,
    fontWeight: "600",
    color: "#5B6572",
  },
  klDetailTabTextActive: {
    color: "#17305D",
    fontWeight: "800",
  },
  klDetailClose: {
    marginLeft: "auto",
    padding: 8,
  },
  klDetailBody: {
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  klDetailTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: "#17305D",
    marginBottom: 3,
  },
  klDetailLine: {
    fontSize: 11,
    color: "#334155",
    marginBottom: 2,
  },
  klDetailDescription: {
    fontSize: 11,
    color: "#475569",
    marginTop: 4,
    marginBottom: 10,
  },
  klNoteRow: {
    borderBottomWidth: 1,
    borderBottomColor: "#EDEFF2",
    paddingVertical: 5,
  },
  klNoteMeta: {
    fontSize: 10,
    color: "#8090A6",
    marginBottom: 1,
  },
  klNoteContent: {
    fontSize: 11,
    color: "#334155",
  },
});
